### ISSUE TITLE
【TODO】0.3.2

### ISSUE THREAD

**Issue by obemaru4012** [obemaru4012/bamboo_websocket#22]
* [ ] Redisを利用したPub/Sub機能を作成する。
* [x] NoMaskedFrameReceiveErrorを追加。
* [x] Bootstrap -> Bulma CSSへ変更。
* [ ] <s>エラーメッセージの多言語化。</s> → 英語に変更。
    * [x] jsonはJsonNodeのまま処理をする。 （よってloadServerSetting()を修正。JsonNodeは「.getStr()」でstring型に変換できる。」
    * [x] 設定ファイルのチェック処理追加。
* [ ] コメントの類を英語に修正する。 
* [ ] Nim Ver2.0対応実施予定。
    * [ ] json paser周りに手が入るみたいなので要チェック。

**Comment by obemaru4012** [comment]
残課題は0.3.3に渡す。
